[package]
name = "rebrickable_server_api"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { workspace = true }
rebrickable_database_api = { workspace = true }

serde = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
