[package]
name = "tui_bricks_update_image"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { workspace = true }
rebrickable_client = { workspace = true }
rebrickable_database_api = { workspace = true }

clap = { workspace = true }
