[package]
name = "tui_bricks2"
version = "0.1.0"
edition = "2024"

[dependencies]
term_lib = { path = "../../term_lib/" }

rebrickable_database_api = { workspace = true }
rebrickable_database = { workspace = true }
rebrickable_client = { workspace = true }

serde = { workspace = true }
